export {
  loadBudgetPageBySlug,
  loadBudgetPages,
  loadCurrentJobOffers,
  loadCurrentGovernmentMembers,
  loadEventBySlug,
  loadEvents,
  loadFeaturedPressReleases,
  loadFreestatePageBySlug,
  loadFreestatePages,
  loadGovernmentMemberBySlug,
  loadGovernmentMembers,
  loadJobOfferBySlug,
  loadJobOffers,
  loadMinistries,
  loadMinistryBySlug,
  loadPageBySlug,
  loadPages,
  loadPressReleaseBySlug,
  loadPressReleases,
  loadRecentPressReleases,
  loadSpeechBySlug,
  loadSpeeches,
  loadTopicBySlug,
  loadTopics,
} from './loader.ts';
