export {
  loadBudgetPageBySlug,
  loadBudgetPages,
  loadBeteiligungsInventar,
  loadBeteiligungsUebersicht,
  loadCabinetArchiveDetailSlugs,
  loadCabinetArchives,
  loadCabinetPageContent,
  loadCurrentJobOffers,
  loadCurrentGovernmentMembers,
  loadCurrentGovernment,
  loadEventBySlug,
  loadEvents,
  loadFeaturedPressReleases,
  loadFreestatePageBySlug,
  loadFreestatePages,
  loadGovernmentMemberBySlug,
  loadGovernmentMembers,
  loadGovernmentProfiles,
  loadHomeContent,
  loadJobOfferBySlug,
  loadJobOffers,
  loadMinistries,
  loadMinistryProfiles,
  loadMinistryBySlug,
  loadOrganizationData,
  loadPageBySlug,
  loadPages,
  loadPressReleaseBySlug,
  loadPressReleases,
  loadRecentPressReleases,
  loadSpeechBySlug,
  loadSpeeches,
  loadTopicBySlug,
  loadTopics,
  type Kabinettsarchiv,
} from '@ostrecht/shared/lib/portal/loader.ts';
