export {
  ContentValidationError,
  HISTORY_ENTRY_TYPES,
  NORM_STATUSES,
  NORM_TYPES,
  STRUCTURE_TYPES,
  parseNormHistory,
  parseNormMeta,
  parseNormVersion,
  validateNormRecord,
  type HistoryEntryType,
  type NormBodyBlock,
  type NormHistory,
  type NormHistoryEntry,
  type NormMeta,
  type NormRecord,
  type NormStatus,
  type NormType,
  type NormVersion,
  type StructureType,
} from '@ostrecht/shared/lib/norms/schema.ts';

export {
  getAccessibilityUrl,
  getAdministrativeRulesUrl,
  getFundingUrl,
  getHomeUrl,
  getHelpUrl,
  getImprintUrl,
  getIndexUrl,
  getIndexGroups,
  getGermanIndexLetter,
  getLawConstitutionUrl,
  getLawFundingUrl,
  getLawHelpUrl,
  getLawPublicationsUrl,
  getLawPortalUrl,
  getLawsUrl,
  getNormCompareUrl,
  getNormCompareDataUrl,
  getNormCompareSelectionUrl,
  getNormHistoryUrl,
  getNormUrl,
  getNormVersionUrl,
  getPublicationEntriesUrl,
  getPublicationUrl,
  getPublicationsUrl,
  getRegulationsUrl,
  getPrivacyUrl,
  getServiceOverviewUrl,
  getSearchUrl,
  getSubjectAreaGroups,
  getSubjectGroups,
  getSubjectSlug,
  getSubjectUrl,
  getSubjectsUrl,
  type SubjectAreaGroup,
  type SubjectGroup,
} from '@ostrecht/shared/lib/norms/routes.ts';

export {
  buildNormPublicationReferenceLookup,
  comparePublicationsNewestFirst,
  findPublicationByDesignation,
  getPublicationDesignations,
  getLatestPublication,
  getNormPublicationReference,
  getPublicationLabel,
  getPublicationSearchAliases,
  hasNumberedIssue,
  listPublicationEntries,
  loadAllVerkuendungen,
  loadVerkuendung,
  parseVerkuendung,
  type NormPublicationReference,
  type PublicationEntryType,
  type Verkuendung,
  type VerkuendungEntry,
} from '@ostrecht/shared/lib/norms/publications.ts';

export {
  buildNormAnchorMap,
  formatNormStatus,
  formatNormType,
  getBlockAnchorId,
  getNormSortKey,
  getNormSortWord,
  getResolvedBlockAnchorId,
  toDisplayText,
  type NormAnchorMap,
  type TextLinkReference,
} from '@ostrecht/shared/lib/norms/presentation.ts';
export {
  buildNormOutline,
  formatDate,
  formatPublicationEntryType,
  getLegacyBlockAnchorId,
  getHeadingTag,
  getNormTitleBlock,
  parseCitation,
  renderLinkedDisplayText,
  type NormOutlineItem,
  type NormTitleBlock,
  type ParsedCitation,
} from '@ostrecht/shared/lib/norms/display.ts';
export {
  buildNormFullCitation,
  buildNormRecordLookup,
  type NormRecordLookup,
} from '@ostrecht/shared/lib/norms/citation.ts';
export {
  getNormVersionIdentity,
  getPublicNormSummary,
  type NormVersionIdentity,
} from '@ostrecht/shared/lib/norms/identity.ts';
export {
  EDITORIAL_REFERENCE_DATE,
  EDITORIAL_TIME_ZONE,
  getBerlinCalendarDate,
  isStrictlyFutureEffectiveDate,
  partitionDatedEntries,
  LEGAL_CHANGE_ENTRY_TYPES,
  VERSION_TEMPORAL_KINDS,
  classifyNormVersion,
  classifyNormVersions,
  getApplicableVersion,
  getNormLastActivityDate,
  getNormLastChangeDate,
  validateVersionIntervals,
  type ClassifiedNormVersion,
  type VersionTemporalKind,
} from '@ostrecht/shared/lib/norms/versions.ts';
export {
  LEGAL_BASELINE_DATE,
  NORM_ORIGIN_KINDS,
  formatNormOriginKind,
  getBaselineVersion,
  getNormOriginInfo,
  getOwnNormChanges,
  type NormOriginInfo,
  type NormOriginKind,
  type OwnNormChange,
} from '@ostrecht/shared/lib/norms/origin.ts';
export {
  classifyNormOriginVersion,
  describeNormOriginKind,
  formatNormOriginBadge,
  type NormOriginBadgeVariant,
  type NormOriginVersionKind,
} from '@ostrecht/shared/lib/norms/origin-presentation.ts';
export {
  NORM_RELATION_KINDS,
  buildNormRelations,
  type NormRelation,
  type NormRelationKind,
  type NormRelationLookup,
} from '@ostrecht/shared/lib/norms/relations.ts';
export {
  buildStructuralVersionDiff,
  diffSentences,
  diffWords,
  flattenVersionUnits,
  summarizeNormDiff,
  type NormDiffKind,
  type NormDiffSummary,
  type NormDiffUnit,
} from '@ostrecht/shared/lib/norms/diff.ts';
export {
  buildNormTextLinkReferences,
  getRelatedNormRecommendations,
  getRelatedNormsBySubjects,
  type RelatedNormRecommendation,
} from '@ostrecht/shared/lib/norms/references.ts';
export {
  INVENTORY_SQL,
  isInheritedAmendment,
  type InventoryStats,
} from '@ostrecht/shared/lib/norms/inventory.ts';
export {
  REGISTER_PATH,
  REGISTER_SCHEMA,
  loadKeywordRegister,
  parseKeywordRegister,
  registerKeywordKey,
  registerKeywordsBySlug,
  type KeywordRegister,
  type RegisterEntry,
} from '@ostrecht/shared/lib/norms/register.ts';
export {
  compareSubjects,
  formatSubjectLabel,
  fundingAreaFromFsn,
  getFundingAreaByNumber,
  getSubjectByNumber,
  getSubjectByTitle,
  getSubjectGroupOf,
  lawFundingAreas,
  lawSubjectGroups,
  lawSubjects,
  subjectNumberFromFsn,
  type LawFundingAreaDefinition,
  type LawSubjectDefinition,
  type LawSubjectGroupDefinition,
} from '@ostrecht/shared/config/law-subjects.ts';
export {
  formatChangedUnitCount,
  formatNormUnitKind,
  getNormUnitKind,
  type NormUnitKind,
} from '@ostrecht/shared/lib/norms/units.ts';
