export {
  ContentValidationError,
  HISTORY_ENTRY_TYPES,
  NORM_STATUSES,
  NORM_TYPES,
  STRUCTURE_TYPES,
  parseNormHistory,
  parseNormMeta,
  parseNormVersion,
  validateNormRecord,
  type HistoryEntryType,
  type NormBodyBlock,
  type NormHistory,
  type NormHistoryEntry,
  type NormMeta,
  type NormRecord,
  type NormStatus,
  type NormType,
  type NormVersion,
  type StructureType,
} from '@ostrecht/shared/lib/norms/schema.ts';

export {
  getAccessibilityUrl,
  getAdministrativeRulesUrl,
  getFundingUrl,
  getHomeUrl,
  getHelpUrl,
  getImprintUrl,
  getIndexUrl,
  getIndexGroups,
  getGermanIndexLetter,
  getLawConstitutionUrl,
  getLawDevelopmentOverviewUrl,
  getLawDevelopmentUrl,
  getLawFundingUrl,
  getLawHelpUrl,
  getLawPublicationsUrl,
  getLawReferencesUrl,
  getLawPortalUrl,
  getLawsUrl,
  getNormCompareUrl,
  getNormCompareDataUrl,
  getNormCompareSelectionUrl,
  getNormHistoryUrl,
  getNormUrl,
  getNormVersionUrl,
  getPublicationUrl,
  getPublicationsUrl,
  getRegulationsUrl,
  getPrivacyUrl,
  getReferencesUrl,
  getServiceOverviewUrl,
  getSearchUrl,
  getSubjectAreaGroups,
  getSubjectGroups,
  getSubjectSlug,
  getSubjectUrl,
  getSubjectsUrl,
  type SubjectAreaGroup,
  type SubjectGroup,
} from '@ostrecht/shared/lib/norms/routes.ts';

export {
  buildNormPublicationReferenceLookup,
  findPublicationByDesignation,
  formatPublicationEntryType,
  getPublicationDesignations,
  getLatestPublication,
  getNormPublicationReference,
  getPublicationLabel,
  getPublicationSearchAliases,
  listPublicationEntries,
  loadAllVerkuendungen,
  loadVerkuendung,
  parseVerkuendung,
  type NormPublicationReference,
  type PublicationEntryType,
  type Verkuendung,
  type VerkuendungEntry,
} from '@ostrecht/shared/lib/norms/publications.ts';

export {
  buildNormAnchorMap,
  buildNormOutline,
  formatDate,
  formatNormStatus,
  formatNormType,
  getBlockAnchorId,
  getLegacyBlockAnchorId,
  getResolvedBlockAnchorId,
  getHeadingTag,
  parseCitation,
  renderLinkedDisplayText,
  toDisplayText,
  type NormOutlineItem,
  type NormAnchorMap,
  type ParsedCitation,
  type TextLinkReference,
} from '@ostrecht/shared/lib/norms/presentation.ts';
export {
  buildNormFullCitation,
  buildNormRecordLookup,
  type NormRecordLookup,
} from '@ostrecht/shared/lib/norms/citation.ts';
export {
  getNormVersionIdentity,
  type NormVersionIdentity,
} from '@ostrecht/shared/lib/norms/identity.ts';
export {
  EDITORIAL_REFERENCE_DATE,
  EDITORIAL_TIME_ZONE,
  getBerlinCalendarDate,
  isStrictlyFutureEffectiveDate,
  partitionDatedEntries,
  VERSION_TEMPORAL_KINDS,
  classifyNormVersion,
  classifyNormVersions,
  formatVersionTemporalLabel,
  getApplicableVersion,
  validateVersionIntervals,
  type ClassifiedNormVersion,
  type VersionTemporalKind,
} from '@ostrecht/shared/lib/norms/versions.ts';
export {
  LEGAL_BASELINE_DATE,
  NORM_ORIGIN_KINDS,
  classifyNormOriginVersion,
  formatNormOriginKind,
  getBaselineVersion,
  getNormOriginInfo,
  getOwnNormChanges,
  type NormOriginInfo,
  type NormOriginKind,
  type NormOriginVersionKind,
  type OwnNormChange,
} from '@ostrecht/shared/lib/norms/origin.ts';
export {
  NORM_RELATION_KINDS,
  buildNormRelations,
  type NormRelation,
  type NormRelationKind,
  type NormRelationLookup,
} from '@ostrecht/shared/lib/norms/relations.ts';
export {
  buildStructuralVersionDiff,
  diffSentences,
  diffWords,
  flattenVersionUnits,
  summarizeNormDiff,
  type NormDiffKind,
  type NormDiffSummary,
  type NormDiffUnit,
} from '@ostrecht/shared/lib/norms/diff.ts';
export {
  buildNormTextLinkReferences,
  getRelatedNormRecommendations,
  getRelatedNormsBySubjects,
  type RelatedNormRecommendation,
} from '@ostrecht/shared/lib/norms/references.ts';
