import { formatDate } from '../lib/norms/presentation.ts';

export const siteConfig = {
  authorityName: 'Staatsregierung des Ostdeutschen Freistaates',
  portalTitle: 'Freistaat Ostdeutschland',
  portalSubtitle: 'Website der Staatsregierung mit Recht, Themen, Presse, Haushalt und Service',
  seo: {
    siteName: 'Freistaat Ostdeutschland',
    siteUrl: 'https://freistaat-ostdeutschland.de',
    locale: 'de_DE',
    defaultDescription:
      'Website der Staatsregierung des Ostdeutschen Freistaates mit Staatsregierung, Themen, Recht, Presse, Haushalt und Service innerhalb einer fiktiven Politiksimulation.',
  },
  simulationNotice:
    'Dies ist eine fiktive Website innerhalb einer politischen Simulation des Ostdeutschen Freistaates.',
  footerNote:
    'Website der Staatsregierung des Ostdeutschen Freistaates mit integriertem Rechtsbereich innerhalb einer fiktiven Politiksimulation.',
  officialFlagAssetPath: '/images/ui/ost-flagge.png',
  officialFlagText: 'OF',
  searchLabel: 'Portal durchsuchen',
  searchPlaceholder: 'z. B. Thema, Ressort, Recht oder Presse',
  paths: {
    home: '/',
    search: '/suche/',
    government: '/staatsregierung/',
    governmentMembers: '/staatsregierung/mitglieder/',
    ministerPresident: '/staatsregierung/ministerpraesident/',
    cabinet: '/staatsregierung/kabinett/',
    coalition: '/staatsregierung/koalition/',
    actionPlan: '/staatsregierung/15-punkte-plan/',
    topics: '/themen/',
    press: '/presse/',
    pressReleases: '/presse/pressemitteilungen/',
    pressSpeeches: '/presse/reden/',
    pressDates: '/presse/termine/',
    budget: '/haushalt/',
    freestate: '/freistaat/',
    service: '/service/',
    serviceOverview: '/service/uebersicht/',
    career: '/service/karriere/',
    faq: '/service/faq/',
    lawHome: '/recht/',
    lawSearch: '/recht/suche/',
    lawIndex: '/recht/archiv/',
    lawSubjects: '/recht/sachgebiete/',
    lawConstitution: '/recht/verfassung/',
    contact: '/service/kontakt/',
    imprint: '/service/impressum/',
    privacy: '/service/datenschutz/',
    accessibility: '/service/barrierefreiheit/',
  },
  mainNavigation: [
    { label: 'Staatsregierung', pathKey: 'government' },
    { label: 'Themen & Projekte', pathKey: 'topics' },
    { label: 'Recht', pathKey: 'lawHome' },
    { label: 'Presse & Aktuelles', pathKey: 'press' },
    { label: 'Haushalt', pathKey: 'budget' },
    { label: 'Über den Freistaat', pathKey: 'freestate' },
    { label: 'Service', pathKey: 'service' },
  ],
  serviceNavigation: [
    { label: 'Übersicht', pathKey: 'serviceOverview' },
    { label: 'Kontakt', pathKey: 'contact' },
    { label: 'Impressum', pathKey: 'imprint' },
    { label: 'Datenschutz', pathKey: 'privacy' },
    { label: 'Barrierefreiheit', pathKey: 'accessibility' },
  ],
  contact: {
    authorityShort: 'Staatsregierung des Ostdeutschen Freistaates',
    addressLines: ['Archivstraße 1', '01097 Dresden'],
    postalAddress: 'Staatskanzlei des Ostdeutschen Freistaates, Archivstraße 1, 01097 Dresden',
    citizenService: {
      label: 'Bürgertelefon',
      phone: '+49 351 100-0',
      email: 'service@osten.de',
    },
    pressOffice: {
      label: 'Pressestelle der Staatsregierung',
      phone: '+49 351 100-1111',
      email: 'pressestelle@osten.de',
    },
    officeHours: ['Montag bis Donnerstag: 9.00 bis 17.00 Uhr', 'Freitag: 9.00 bis 15.00 Uhr'],
  },
  currentGovernment: {
    cabinetName: 'Kabinett Honecker',
    formedOn: '2025-12-20',
    coalition: 'Volksfront und DEMOS Ost',
    coalitionShort: 'Volksfront · DEMOS Ost',
    coalitionParties: ['Volksfront', 'DEMOS Ost'],
    headOfGovernment: 'Dr. Karl Honecker',
    deputyHead: 'Mia Wollrath',
    legislature: '6. Ostdeutscher Landtag',
    predecessor: 'Kabinett Delgado',
    seatOfGovernment: 'Dresden',
  },
  date: {
    formatLong: formatDate,
  },
} as const;

export type SiteConfig = typeof siteConfig;
export type SitePathKey = keyof typeof siteConfig.paths;
